from transformers import (
    Qwen3VLForConditionalGeneration,
    Qwen3VLMoeForConditionalGeneration,
    AutoProcessor,
)
from collections import OrderedDict

from optimum.quanto import freeze
from toolkit.basic import flush
from toolkit.util.quantize import quantize, get_qtype

from .BaseCaptioner import BaseCaptioner
import transformers
import logging
import warnings
from pathlib import Path

# transformers.logging.set_verbosity_error()
warnings.filterwarnings("ignore")
logging.disable(logging.WARNING)

WD_PROMPT_TEMPLATE = """Below is a list of candidate danbooru-style tags generated by an
automatic tagger (WD tagger) at a low confidence threshold for this image.
Look at the image directly and clean up the list according to the rules below.

Rules:
1. Use only tags that appear in the candidate list. Do not add any new tag
   that is not already in the list.
2. Remove tags that clearly contradict the image (e.g. mutually exclusive
   attributes appearing together) or that cannot be visually confirmed.
3. If multiple tags refer to the same thing (duplicates or synonyms), keep
   only one of them.
4. If you are not confident about a tag, keep it rather than removing it
   (do not over-prune).
5. Output a single line of tags separated by commas only. Do not include
   any explanation, numbering, quotation marks, or extra sentences.

Candidate tags:
{tags}

Cleaned tags:"""

class Qwen3VLCaptioner(BaseCaptioner):
    def __init__(self, process_id: int, job, config: OrderedDict, **kwargs):
        super(Qwen3VLCaptioner, self).__init__(process_id, job, config, **kwargs)

    def load_model(self):
        self.print_and_status_update("Loading Qwen3VL model")
        ModelClass = (
            Qwen3VLMoeForConditionalGeneration
            if "B-A" in self.caption_config.model_name_or_path
            else Qwen3VLForConditionalGeneration
        )
        self.model = ModelClass.from_pretrained(
            self.caption_config.model_name_or_path,
            dtype=self.torch_dtype,
            device_map="cpu",
        )
        if not self.caption_config.low_vram:
            self.model.to(self.device_torch)
        if self.caption_config.quantize:
            self.print_and_status_update("Quantizing Qwen3VL model")
            quantize(self.model, weights=get_qtype(self.caption_config.qtype))
            freeze(self.model)
            flush()
        self.processor = AutoProcessor.from_pretrained(
            self.caption_config.model_name_or_path
        )
        if self.caption_config.low_vram:
            self.model.to(self.device_torch)
        flush()

    def load_candidate_tags(self, img_path: str) -> list[str]:
        txt_path = Path(img_path).with_suffix(".txt")
        raw = txt_path.read_text(encoding="utf-8").strip()
        tags = [t.strip() for t in raw.split(",") if t.strip()]
        return tags

    def wd_parse_and_validate(self, raw_output: str, candidate_tags: list[str]) -> list[str]:
        """모델 출력 텍스트를 파싱하고, 후보 목록에 없는 태그(hallucination)는
        안전망으로 강제 제거한다. 순서는 후보 목록 순서를 따르고 중복은 제거한다."""
        import re
        # 모델이 가끔 앞뒤에 군더더기를 붙이는 경우 대비: 콤마가 포함된 줄만 사용
        line = raw_output.strip().splitlines()[-1] if raw_output.strip() else ""
        raw_tags = [re.sub(r'^[\'"]|[\'"]$', "", t.strip()) for t in line.split(",")]
        raw_tags = [t for t in raw_tags if t]

        candidate_set_lower = {c.lower(): c for c in candidate_tags}
        kept_lower = {t.lower() for t in raw_tags if t.lower() in candidate_set_lower}

        # 후보 목록 순서를 유지하면서 중복 없이 최종 리스트 구성
        return [orig for low, orig in candidate_set_lower.items() if low in kept_lower]

    def get_caption_for_file(self, file_path: str) -> str:
        img = self.load_pil_image(file_path, max_res=self.caption_config.max_res)
        try:
            if self.caption_config.wd_caption:
                candidate_tags = self.load_candidate_tags(file_path)
                prompt = WD_PROMPT_TEMPLATE.format(tags=", ".join(candidate_tags))
            else:
                prompt = self.caption_config.caption_prompt

            messages = [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image",
                            "image": img,
                        },
                        {"type": "text", "text": prompt},
                    ],
                }
            ]

            # Preparation for inference
            inputs = self.processor.apply_chat_template(
                messages,
                tokenize=True,
                add_generation_prompt=True,
                return_dict=True,
                return_tensors="pt",
            )
            inputs = inputs.to(self.device_torch)

            options = {"max_new_tokens":self.caption_config.max_new_tokens}
            if self.caption_config.wd_caption:
                options.update({"do_sample":False})

            # Inference: Generation of the output
            generated_ids = self.model.generate(
                **inputs, **options,
            )
            generated_ids_trimmed = [
                out_ids[len(in_ids) :]
                for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
            ]
            output_text = self.processor.batch_decode(
                generated_ids_trimmed,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=False,
            )

            raw_output = output_text[0].strip()

            if self.caption_config.wd_caption:
                cleaned_tags = self.wd_parse_and_validate(raw_output, candidate_tags)
                if not cleaned_tags:
                    print(f"[warn] {file_path}: 정리 결과가 비었음, 원본 후보 유지")
                    cleaned_tags = candidate_tags
                raw_output = ", ".join(cleaned_tags)

            return raw_output
        except Exception as e:
            print(f"Error processing {file_path}: {e}")
            return None
