from transformers import (
    AutoModelForImageTextToText,
    AutoProcessor,
    StoppingCriteria,
    StoppingCriteriaList,
)
from collections import OrderedDict

import torch
import torch.nn.functional as F
from optimum.quanto import freeze
from toolkit.basic import flush
from toolkit.util.quantize import quantize, get_qtype

from .BaseCaptioner import BaseCaptioner
import transformers
import logging
import traceback
import warnings
from pathlib import Path


def patch_qwen_vl_patch_embed(model):
    """Qwen-VL's vision patch_embed is a Conv3d whose kernel == stride, i.e. a plain
    linear projection of each flattened patch. bf16 Conv3d has no fast cuDNN kernel and
    falls back to a slow, GPU-underutilizing path. Swap it for the equivalent F.linear
    (a GEMM). The weight is read lazily so this survives later .to(device)/dtype moves.
    Returns the number of patch_embed modules patched."""
    patched = 0
    for module in model.modules():
        proj = getattr(module, "proj", None)
        if isinstance(proj, torch.nn.Conv3d) and tuple(proj.kernel_size) == tuple(
            proj.stride
        ):

            def fast_forward(hidden_states, _proj=proj):
                w = _proj.weight.reshape(_proj.weight.shape[0], -1)
                x = hidden_states.view(-1, w.shape[1]).to(w.dtype)
                return F.linear(x, w, _proj.bias)

            module.forward = fast_forward
            patched += 1
    return patched


# transformers.logging.set_verbosity_error()
warnings.filterwarnings("ignore")
logging.disable(logging.WARNING)

WD_PROMPT_TEMPLATE = """Below is a list of candidate danbooru-style tags generated by an
automatic tagger (WD tagger) at a low confidence threshold for this image.
Look at the image directly and clean up the list according to the rules below.

Rules:
1. Use only tags that appear in the candidate list. Do not add any new tag
   that is not already in the list.
2. Remove tags that clearly contradict the image (e.g. mutually exclusive
   attributes appearing together) or that cannot be visually confirmed.
3. If multiple tags refer to the same thing (duplicates or synonyms), keep
   only one of them.
4. If you are not confident about a tag, keep it rather than removing it
   (do not over-prune).
5. Output a single line of tags separated by commas only. Do not include
   any explanation, numbering, quotation marks, or extra sentences.

Candidate tags:
{tags}

Cleaned tags:"""
# hard cap on reasoning tokens so a runaway think block cannot generate forever
MAX_THINKING_TOKENS = 4096


class ThinkingBudgetCriteria(StoppingCriteria):
    """For thinking models: lets the model reason freely, then counts
    max_new_tokens starting from the token after </think> so the visible answer
    gets the full budget regardless of how long the reasoning ran."""

    def __init__(self, think_end_token_id: int, max_new_tokens: int):
        self.think_end_token_id = think_end_token_id
        self.max_new_tokens = max_new_tokens
        self.answer_start = None

    def __call__(self, input_ids, scores, **kwargs):
        if self.answer_start is None:
            if input_ids[0, -1].item() == self.think_end_token_id:
                self.answer_start = input_ids.shape[1]
            return False
        return (input_ids.shape[1] - self.answer_start) >= self.max_new_tokens


class Qwen3VLCaptioner(BaseCaptioner):
    def __init__(self, process_id: int, job, config: OrderedDict, **kwargs):
        super(Qwen3VLCaptioner, self).__init__(process_id, job, config, **kwargs)

    def load_model(self):
        self.print_and_status_update("Loading Qwen3VL model")
        self.model = AutoModelForImageTextToText.from_pretrained(
            self.caption_config.model_name_or_path,
            dtype=self.torch_dtype,
            device_map="cpu",
        )
        # swap the slow bf16 Conv3d patch_embed for an equivalent fast linear
        patch_qwen_vl_patch_embed(self.model)
        if not self.caption_config.low_vram:
            self.model.to(self.device_torch)
        if self.caption_config.quantize:
            self.print_and_status_update("Quantizing Qwen3VL model")
            # in low vram mode the model stays on cpu; quantize each layer on the
            # gpu and move it back so the math is fast without holding the whole
            # model in vram
            # lm_head is huge (vocab x hidden) and quality-critical; quantizing it
            # needs a ~4x transient allocation that can OOM, so keep it in full
            # precision
            quantize(
                self.model,
                weights=get_qtype(self.caption_config.qtype),
                exclude=["lm_head", "*.lm_head"],
                quantize_device=self.device_torch
                if self.caption_config.low_vram
                else None,
            )
            freeze(self.model)
            flush()
        self.processor = AutoProcessor.from_pretrained(
            self.caption_config.model_name_or_path
        )
        if self.caption_config.low_vram:
            self.model.to(self.device_torch)
        flush()

    def load_candidate_tags(self, img_path: str) -> list[str]:
        txt_path = Path(img_path).with_suffix(".txt")
        raw = txt_path.read_text(encoding="utf-8").strip()
        tags = [t.strip() for t in raw.split(",") if t.strip()]
        return tags

    def wd_parse_and_validate(self, raw_output: str, candidate_tags: list[str]) -> list[str]:
        """모델 출력 텍스트를 파싱하고, 후보 목록에 없는 태그(hallucination)는
        안전망으로 강제 제거한다. 순서는 후보 목록 순서를 따르고 중복은 제거한다."""
        import re
        # 모델이 가끔 앞뒤에 군더더기를 붙이는 경우 대비: 콤마가 포함된 줄만 사용
        line = raw_output.strip().splitlines()[-1] if raw_output.strip() else ""
        raw_tags = [re.sub(r'^[\'"]|[\'"]$', "", t.strip()) for t in line.split(",")]
        raw_tags = [t for t in raw_tags if t]

        candidate_set_lower = {c.lower(): c for c in candidate_tags}
        kept_lower = {t.lower() for t in raw_tags if t.lower() in candidate_set_lower}

        # 후보 목록 순서를 유지하면서 중복 없이 최종 리스트 구성
        return [orig for low, orig in candidate_set_lower.items() if low in kept_lower]

    def get_caption_for_file(self, file_path: str) -> str:
        img = self.load_pil_image(file_path, max_res=self.caption_config.max_res)
        try:
            if self.caption_config.wd_caption:
                candidate_tags = self.load_candidate_tags(file_path)
                prompt = WD_PROMPT_TEMPLATE.format(tags=", ".join(candidate_tags))
            else:
                prompt = self.caption_config.caption_prompt

            messages = [
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image",
                            "image": img,
                        },
                        {"type": "text", "text": prompt},
                    ],
                }
            ]

            # Preparation for inference
            inputs = self.processor.apply_chat_template(
                messages,
                tokenize=True,
                add_generation_prompt=True,
                return_dict=True,
                return_tensors="pt",
                enable_thinking=self.caption_config.thinking,
            )
            inputs = inputs.to(self.device_torch)

            gen_kwargs = {"max_new_tokens": self.caption_config.max_new_tokens}
            if self.caption_config.wd_caption:
                gen_kwargs.update({"do_sample":False})
            if self.caption_config.thinking:
                think_end_token_id = self.processor.tokenizer.convert_tokens_to_ids(
                    "</think>"
                )
                if think_end_token_id is not None:
                    # give the model room to think, but start the max_new_tokens
                    # budget only once the think block closes
                    gen_kwargs = {
                        "max_new_tokens": MAX_THINKING_TOKENS
                        + self.caption_config.max_new_tokens,
                        "stopping_criteria": StoppingCriteriaList(
                            [
                                ThinkingBudgetCriteria(
                                    think_end_token_id,
                                    self.caption_config.max_new_tokens,
                                )
                            ]
                        ),
                    }

            # Inference: Generation of the output
            generated_ids = self.model.generate(**inputs, **gen_kwargs)
            generated_ids_trimmed = [
                out_ids[len(in_ids) :]
                for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
            ]
            output_text = self.processor.batch_decode(
                generated_ids_trimmed,
                skip_special_tokens=True,
                clean_up_tokenization_spaces=False,
            )

            caption = output_text[0]
            if self.caption_config.wd_caption:
                cleaned_tags = self.wd_parse_and_validate(caption, candidate_tags)
                if not cleaned_tags:
                    print(f"[warn] {file_path}: 정리 결과가 비었음, 원본 후보 유지")
                    cleaned_tags = candidate_tags
                caption = ", ".join(cleaned_tags)
            # thinking models (e.g. Qwen3.6) may still emit reasoning before the
            # answer; keep only what follows the think block
            if "</think>" in caption:
                caption = caption.split("</think>")[-1]
            return caption.strip()
        except Exception as e:
            print(f"Error processing {file_path}: {e}")
            traceback.print_exc()
            return None
